title: Split.it
description: Cost-pooling made easy.
show_downloads: false
google_analytics:
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
github:
  repository_url: https://github.com/trysplit-it